### ISSUE TITLE
图书介绍无法通过sel.xpath('.//*[@id="iframeContent"]')来抓取

### ISSUE THREAD

**Issue by sunzy** [imaginezz/amazonBookSpider#1]
亚马逊的图书介绍无法通过sel.xpath('.//*[@id="iframeContent"]')来抓取

图书介绍被写在bookDescEncodedData的js变量中，在页面加载完后，生成iframe,写到bookDesc_iframe_wrapper中的。
通过id="bookDesc_iframe_wrapper"获取到的是个空的DIV
通过id="iframeContent"获取的是NULL

请问大神有什么方法能解决吗？

**Comment by sunzy** [comment]
搜一下，大致的意思是要写scrapy的中间件，比如PhantomJS

**Comment by imaginezz** [comment]
我觉得可以直接将iframe的url找到，然后再爬取那个页面解决。

**Comment by sunzy** [comment]
不是，这个iframe不是通过URL来加载的，图书的介绍保存在bookDescEncodedData这个JS变量里，通过JS动态生成的这个iframe。
使用PhantomJS可以拿到当当的图书信息（同样的JS加载的），却拿不到亚马逊的，还没弄清楚是怎么回事

**Comment by imaginezz** [comment]
这样啊，我去研究一下这个问题

Get Outlook for iOS

On Sun, Sep 25, 2016 at 3:31 PM +0800, "sunzy" notifications@github.com wrote:

不是，这个iframe不是通过URL来加载的，图书的介绍保存在bookDescEncodedData这个JS变量里，通过JS动态生成的这个iframe。
使用PhantomJS可以拿到当当的图书信息（同样的JS加载的），却拿不到亚马逊的，还没弄清楚是怎么回事

##
